spring.application.name=ai-interview-backend

# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8081}


# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}


# =========================================================
# GEMINI
# =========================================================

gemini.api-key=${GEMINI_API_KEY}